spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
#    url: jdbc:postgresql://some-postgres:5432/postgres  #prod
    url: jdbc:postgresql://localhost:5432/postgres      #dev
    username: postgres
  jpa:
    hibernate:

      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console

#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
  credentials:
    admin1:
      email: marley@gmail.com
      password: password
    user1:
      email: user1@gmail.com
      password: user1
  initData:
    localizationsFileName: "localizations.xlsx"
    equipmentsFileName: "equipments.xlsx"



